### PR TITLE
fix: JsonDeserializer accepts content-type header with charset

### LINKED ISSUE #61: JsonDeserializer does not accept content-type header with charset
## Describe the bug
JsonDeserializer does not accept content-type header with charset

## To Reproduce
use header: `Content-Type: application/json; charset=utf-8`

## Expected behavior
`bodyObject` should not be null

## Additional context
nope

### PR DESCRIPTION
**Pull request by buresmi7**
Closes #61 

## Checklist:

- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by dbartholomae** [comment]
Thanks! Could you run `rush change` in the branch and commit the created change file? It will be used to create the change log.

File: packages/json-deserializer/src/JsonDeserializer.ts [hunk 1]
```diff
@@ -49,11 +49,15 @@ const isJsonMimeType = (event: APIGatewayProxyEvent) => {
 
   const mimeParts = contentTypeHeader.split("/");
 
+  if (mimeParts[1].includes(";")) {
+    mimeParts[1] = mimeParts[1].split(";")[0];
+  }
+
```
Comment (dbartholomae) [inline packages/json-deserializer/src/JsonDeserializer.ts:55]: I think this could be simplified to

```suggestion
  const MIME_TYPE_REGEX = /(.+)\/(.+);.+/;
  const mimeParts = MIME_TYPE_REGEX.exec(contentTypeHeader).slice(1);
```

**Review by dbartholomae — CHANGES_REQUESTED** [review]

File: packages/json-deserializer/src/JsonDeserializer.ts (hunk 1 above)
Comment (buresmi7) [reply packages/json-deserializer/src/JsonDeserializer.ts:55]: Why not:

Comment (buresmi7) [reply packages/json-deserializer/src/JsonDeserializer.ts:55]: I check https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types and there are only two options allowed with `json`, so what about this:
```
const MIME_TYPE_REGEX = /application\/json|application\/ld\+json/;
if (!contentTypeHeader.match(MIME_TYPE_REGEX)) {
  return false;
}
```

Comment (dbartholomae) [reply packages/json-deserializer/src/JsonDeserializer.ts:55]: Good point. Maybe the full function could just be
```ts
const isJsonMimeType = (event: APIGatewayProxyEvent) => {
  const { headers } = event;
  const contentTypeHeader =
    headers?.["Content-Type"] ?? headers?.["content-type"] ?? '';
  return contentTypeHeader.startsWith("application/json") || contentTypeHeader.startsWith("application/jd+json");
}
```

**Review by dbartholomae — APPROVED** [review]
Thanks! :)
